name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: sudo apt-get update && sudo apt-get install gcc-riscv64-linux-gnu binutils make
      - name: Build
        run: make
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            fw_payload.bin
